### ISSUE TITLE
Running RPS.Web

### ISSUE THREAD

**Issue by amanda-delongchamp** [alexziskind1/rpstrackeraspmvc#1]
It seems some files are missing?  I'm using VS2019 
![image](https://user-images.githubusercontent.com/44955591/129428939-7e884bd1-9e7d-43f6-a63c-a83ea469d4e1.png)

**Comment by alexziskind1** [comment]
Hello @amanda-delongchamp . Please clean the solution and rebuild. Sometimes you might need to delete the entire Debug folder from the built output.

**Comment by amanda-delongchamp** [comment]
Thank you so much!  It works beautifully now.  :)
